export const PRODUCTS = [
    {
        _id: 0,
        brand: "taude",
        name: "JOY",
        imageUrl: "/images/products/tote21.jpg",
        description: "Simple color and modern shape",
        color: "pink",
        material: "canvas",
        price: 20.90,
        rating: 5,
        numReviews: 10
    },
    {
        _id: 1,
        brand: "taude",
        name: "Black Dot",
        imageUrl: "/images/products/tote12.jpg",
        description: "Simple color and modern shape",
        color: "black",
        material: "leather",
        price: 45.90,
        rating: 4.5,
        numReviews: 23
    },
    {
        _id: 2,
        brand: "taude",
        name: "Cute Box",
        imageUrl: "/images/products/tote27.jpg",
        description: "High quality genuine leather",
        color: "white",
        material: "leather",
        price: 62.90,
        rating: 3.8,
        numReviews: 5
    },
    {
        id: 3,
        brand: "taude",
        name: "Break Silence",
        imageUrl: "/images/products/tote4.jpg",
        description: "Simple color and modern shape",
        color: "white",
        material: "canvas",
        price: 34.50,
        rating: 5,
        numReviews: 18,
    },
    {
        _id: 4,
        brand: "taude",
        name: "Break Silence",
        imageUrl: "/images/products/tote19.jpg",
        description: "Simple color and modern shape",
        color: "blue",
        material: "canvas",
        price: 18.90,
        rating: 5,
        numReviews: 45
    },
    {
        _id: 5,
        brand: "taude",
        name: "Break Silence",
        imageUrl: "/images/products/tote18.jpg",
        description: "Simple color and modern shape",
        color: "yellow",
        material: "canvas",
        price: 109.80,
        rating: 4.9,
        numReviews: 33
    },
];